CI: Fixes & Updates (#125)
* CI: Setup KernelSU: Remove KernelSU repository included in kernel source

If the kernel source code contains a KernelSU repository (or submodule),
this will cause an error when performing the Setup KernelSU step.

error: pathspec 'main' did not match any file(s) known to git
From: https://github.com/xiaoleGun/KernelSU_Action/issues/123#issue-2089859718

Signed-off-by: bdqllW <bdqllT@gmail.com>

* CI: Add KernelSU version number in upload name

Show in uploads or artifacts

Signed-off-by: bdqllW <bdqllT@gmail.com>

---------

Signed-off-by: bdqllW <bdqllT@gmail.com>